
# This file is automatically generated, you probably don't want to edit this

JARScalesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "JARScalesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            attr = NULL,
            attrscale = "Five",
            lik = NULL,
            threshold = 20,
            mdropthreshold = 1,
            posthoc = FALSE,
            showbarras = FALSE,
            showternary = FALSE,
            showdiagnose = FALSE, ...) {

            super$initialize(
                package="JAR",
                name="JARScales",
                requiresData=TRUE,
                ...)

            private$..attr <- jmvcore::OptionVariables$new(
                "attr",
                attr,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..attrscale <- jmvcore::OptionList$new(
                "attrscale",
                attrscale,
                options=list(
                    "Three",
                    "Five",
                    "Seven",
                    "Nine"),
                default="Five")
            private$..lik <- jmvcore::OptionVariable$new(
                "lik",
                lik,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..threshold <- jmvcore::OptionNumber$new(
                "threshold",
                threshold,
                default=20,
                min=1,
                max=99)
            private$..mdropthreshold <- jmvcore::OptionNumber$new(
                "mdropthreshold",
                mdropthreshold,
                default=1,
                min=0,
                max=10)
            private$..posthoc <- jmvcore::OptionBool$new(
                "posthoc",
                posthoc,
                default=FALSE)
            private$..showbarras <- jmvcore::OptionBool$new(
                "showbarras",
                showbarras,
                default=FALSE)
            private$..showternary <- jmvcore::OptionBool$new(
                "showternary",
                showternary,
                default=FALSE)
            private$..showdiagnose <- jmvcore::OptionBool$new(
                "showdiagnose",
                showdiagnose,
                default=FALSE)

            self$.addOption(private$..attr)
            self$.addOption(private$..attrscale)
            self$.addOption(private$..lik)
            self$.addOption(private$..threshold)
            self$.addOption(private$..mdropthreshold)
            self$.addOption(private$..posthoc)
            self$.addOption(private$..showbarras)
            self$.addOption(private$..showternary)
            self$.addOption(private$..showdiagnose)
        }),
    active = list(
        attr = function() private$..attr$value,
        attrscale = function() private$..attrscale$value,
        lik = function() private$..lik$value,
        threshold = function() private$..threshold$value,
        mdropthreshold = function() private$..mdropthreshold$value,
        posthoc = function() private$..posthoc$value,
        showbarras = function() private$..showbarras$value,
        showternary = function() private$..showternary$value,
        showdiagnose = function() private$..showdiagnose$value),
    private = list(
        ..attr = NA,
        ..attrscale = NA,
        ..lik = NA,
        ..threshold = NA,
        ..mdropthreshold = NA,
        ..posthoc = NA,
        ..showbarras = NA,
        ..showternary = NA,
        ..showdiagnose = NA)
)

JARScalesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "JARScalesResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        Consumidores = function() private$.items[["Consumidores"]],
        MeanDrop = function() private$.items[["MeanDrop"]],
        barraplot = function() private$.items[["barraplot"]],
        ternaplot = function() private$.items[["ternaplot"]],
        diagplot = function() private$.items[["diagplot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Just-About-Right analysis")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Just-About-Right analysis"))
            self$add(jmvcore::Table$new(
                options=options,
                name="Consumidores",
                title="Consumer Research (Attributes)",
                rows="(attr)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Attributes", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="consulow", 
                        `title`="Low (%)", 
                        `type`="number"),
                    list(
                        `name`="consujar", 
                        `title`="Jar (%)", 
                        `type`="number"),
                    list(
                        `name`="consuhigh", 
                        `title`="High (%)", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="MeanDrop",
                title="Mean-drop value (Attributes)",
                rows="(attr)",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Attributes", 
                        `type`="text", 
                        `content`="($key)", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="droplow", 
                        `title`="Mean-Drop Low", 
                        `type`="number"),
                    list(
                        `name`="tukeylow", 
                        `title`="ptukey Low", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="drophigh", 
                        `title`="Mean-Drop High", 
                        `type`="number"),
                    list(
                        `name`="tukeyhigh", 
                        `title`="ptukey High", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="barraplot",
                title="Barplot of attributes",
                width=640,
                height=640,
                renderFun=".plot3",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="ternaplot",
                title="Ternary Plot of attributes",
                width=640,
                height=640,
                renderFun=".plot",
                visible=FALSE))
            self$add(jmvcore::Image$new(
                options=options,
                name="diagplot",
                title="Diagnostic Plot of attributes",
                width=640,
                height=640,
                renderFun=".plot2",
                visible=FALSE))}))

JARScalesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "JARScalesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "JAR",
                name = "JARScales",
                version = c(1,0,0),
                options = options,
                results = JARScalesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Just-About-Right analysis
#'
#' 
#' @param data .
#' @param attr .
#' @param attrscale .
#' @param lik .
#' @param threshold .
#' @param mdropthreshold .
#' @param posthoc .
#' @param showbarras .
#' @param showternary .
#' @param showdiagnose .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$Consumidores} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$MeanDrop} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$barraplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$ternaplot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$diagplot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$Consumidores$asDF}
#'
#' \code{as.data.frame(results$Consumidores)}
#'
#' @export
JARScales <- function(
    data,
    attr,
    attrscale = "Five",
    lik,
    threshold = 20,
    mdropthreshold = 1,
    posthoc = FALSE,
    showbarras = FALSE,
    showternary = FALSE,
    showdiagnose = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("JARScales requires jmvcore to be installed (restart may be required)")

    if ( ! missing(attr)) attr <- jmvcore::resolveQuo(jmvcore::enquo(attr))
    if ( ! missing(lik)) lik <- jmvcore::resolveQuo(jmvcore::enquo(lik))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(attr), attr, NULL),
            `if`( ! missing(lik), lik, NULL))

    for (v in attr) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- JARScalesOptions$new(
        attr = attr,
        attrscale = attrscale,
        lik = lik,
        threshold = threshold,
        mdropthreshold = mdropthreshold,
        posthoc = posthoc,
        showbarras = showbarras,
        showternary = showternary,
        showdiagnose = showdiagnose)

    analysis <- JARScalesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

